### ISSUE TITLE
關於《A Heart Rate Monitoring Framework for Real-World Drivers Using Remote Photoplethysmography》中公式12的問題

### ISSUE THREAD

**Issue by Z-Xiong** [abc1199281/SW_InterviewPrep#1]
您好，我最近在看您的這篇論文，對論文中公式（12）裡的(i-1)，不是很理解，請問它代表的是冪還是導數，或者其他什麼含義？

**Comment by abc1199281** [comment]
hi, 

感謝你閱讀我的論文。(i-1) 代表冪，並非導數，公式12是exponential smoothing的impulse response 表達形式

一種exponential smoothing(ES)相關推導可以參考此文章。同一濾波器，有不同的表達方式，e.g., impulse response (公式12), z-transform (公式6), 或 Difference equation.


https://tttapa.github.io/Pages/Mathematics/Systems-and-Control-Theory/Digital-filters/Exponential%20Moving%20Average/Exponential-Moving-Average.html

**Comment by Z-Xiong** [comment]
非常感謝！我再研究一下。

**Comment by Z-Xiong** [comment]
请问下，您是先做了带通滤波还是先做了AD呢？我在论文中没有看到对应的步骤。

**Comment by abc1199281** [comment]
嗨~
當時並沒有在時域(x[n])進行帶通濾波

請注意，AD是操作在頻域(X[n,0]...X[n,N-1])的bins上, 其中N是DFT的數量
頻譜估算心跳(頻域取peaks)時，可以從對應的band-width(e.g., 30-200bpm) 中取最高的bin(或最高左右幾根內插),進行計算。

有關頻譜估計細節，個人建議參考這本書, 印象chapter10左右, 內有Single tone frequency estmiation的數種方法討論: 
https://www.kobo.com/tw/zh/ebook/statistical-signal-processing-in-engineering

**Comment by Z-Xiong** [comment]
请问AD的操作是在X[n,k]上进行的，还是X[iR,k]上进行的呢？
我对您的算法进行了复现，并使用您论文中的线性调频信号使用matlab进行了仿真，调用matlab中自有的stft函数，得到X[iR,k]，在其结果上进行了AD操作，可以有效消除持续几秒的带限噪声。
另外，按您论文所述，AD算法对持续性的噪声或者强度大于心率信号的噪声效果不佳，请问您在CVPM-2020比赛中获得第三名中使用的AD算法，有做什么参数调节么。因为VIPL数据集中的数据似乎不是很满足您算法的适用条件。

**Comment by Z-Xiong** [comment]
您有对比过加入带通滤波的效果吗？我查看了只进行带通滤波的rppg波形，波形效果还是挺好的，如果不加，波形还是比较混乱。只在频率估计时剔除较低频率以下和较高频率以上的bin，好像效果没有加带通滤波的效果好啊。您在比赛的时候也没有用带通滤波吗？

**Comment by abc1199281** [comment]
1. X[iR,k] 上進行, 考慮hop size (R)
2. AD算法对持续性的噪声或者强度大于心率信号的噪声效果不佳...(後略)... VIPL似乎不滿足使用條件。

-->是的。當初開發此算法時, 並未注意到CVPM競賽, 此算法並非針對VIPL設計，而是針對長時間心跳監控而設計(如論文所述)。

-->限制: AD是一種頻譜估計方法, 僅是整個心跳量測系統中的一環，其準確率深深地受到前面訊號品質(i.e., 持续性的噪声或者强度大于心率信号的噪声效果不佳)。

-->公開之實驗結果也呈現此現象:  CVPM 2020競賽報告[1]中的Figure 4來看，本算法(T3)相較其他算法(T4-T6)，在VIPL上其實沒有顯著的進展。推測原因在於VIPL 較多强度大于心率信号的噪声

-->從[1]中的Figure 4來看，本算法(T3)相較(T4-T6)，在OBF資料庫能顯著降低error。推測可能原因是，AD將snr低於閥值之頻譜訊號阻絕(Smoothing factor = 0)，僅針對有信心的頻譜進行運算，在訊號源相對穩定的情況下(OBF訊號源較VIPL穩定)，AD提取更多有效頻譜成分，進而較準確地預估。

3. 是否有其餘參數調節。

以AD參數來說，頻譜估計雖然有很多細節(e.g., window size, window function, etc), 但只要follow AD核心精神，在SNR低時，smoothing factor = 0 (拒絕該訊號)。就我經驗來說，效果基本上接近。SNR閥值根據使用者選擇之機率決定。如上述, AD僅是整個系統一環，若前端訊號源差，這類傳統頻譜分析方法沒辦法做到無中生有。

若要精進整體心跳量測系統，以下純屬個人經驗分享:
    1. rPPG訊號計算方式
    2. ROI大小: stable scene, ROI大, SNR通常較佳。Unstable scene, ROI大, 可能反而SNR更糟 (容易框到非人臉區)。印象CVPM 2020第二名的方法就是採用非常好的ROI選擇法。

蠻重要所以再敘述一次: AD無法僅是頻譜分析，沒辦法做到無中生有。
[1] https://arxiv.org/pdf/2003.11756.pdf

4. 您有对比过加入带通滤波的效果吗?
-->量測系統最終是採用頻譜來計算心跳。在頻譜分析中，不同頻率成分彼此間orthogonal不互相干擾。帶通濾波是在頻譜分析之前把其餘頻帶的訊號去掉。若頻譜分析時，根本不考慮頻帶外的component，理論上是十分接近的。

**Comment by Z-Xiong** [comment]
感谢您的耐心解答，让我对AD算法有了深入的理解。
1、按您所述，我的理解是，您在CVPM2020中，AD其实只是最后一个步骤对吗？前面还是用了一些使信号质量变好的算法。这解答了我的疑惑，之前我也很难相信只是用STFT+AD就可以取得这么好的成绩。

2、按照AD算法的核心精神，其主要作用是去除信噪比比较低的信号段，是不是基本等效于，将信号分段，并计算每段信号的信噪比，如果该信噪比低于设定阈值，就可以舍去该段信号估计的心率。这样算法就变成了“舍去信噪比较低的信号段+信噪比较好的信号段做STFT”。这里STFT只是替代DFT插值或者直接DFT后频谱取最大值的方法做频率估计。

3、对于您所述的“ROI大小问题”，我经过实验也确实有所体会，在我自建的数据集中，同时保证其他变量不变，稳定场景情况下，距离摄像头1.5米的MAE要远大于距离摄像头0.8米的MAE，应该是较大的ROI取平均可以较好抑制某种类噪声；至于您说的不稳定场景，我认为主要不是框到非人脸区导致的SNR较低，在我的实验中，人脸跟踪如果较为稳定，其框到非人脸区域还是比较少，主要导致SNR较低的原因我认为是在不稳定场景下：人脸距离摄像头左右或前后距离的变化，导致的人脸皮肤上光强的变化。至于CVPM2020第二名所选用的ROI提取的方法，效果较好，我认为是其去除了眼睛、嘴巴等非刚性运动（表情变化）导致的噪声。

4、感觉您很乐于助人，想和您继续请教RPPG的技术，不知方不方便加您的Line或者其他的即时聊天软件账号。如果您担心隐私，可以把账号发到我的邮箱zxiong9397@gmail.com

**Comment by abc1199281** [comment]
Hi Z-Xiong,

1.2., 基本上您已經理解AD的精神，基於其上的各種變形(您說的等校方法)，可能仍有細微的差異(我認為頻譜分析其實是很深的一門學問)，這可能須您更進一步的實驗與探索。

3. 同意~心跳量測存在非常多的細節

4. 十分感謝您對AD的興趣。不好意思，我僅能基於AD之公開內容回復您，不適合揭漏更多細節。
如您所分享的ROI實驗，我理解到您已經對rPPG有深刻了解，真誠祝福您在此領域取得好的進展。
